apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
  labels:
    vol: mongo
spec:
  storageClassName: "my-storage-class"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/Users/vibhor/Documents/manish/Project/appsmith/appsmith/deploy/k8s/volume"
